export const NEW_ACTIVITY_INIT = "NEW_ACTIVITY_INIT";
export const NEW_ACTIVITY_CHANGE = "NEW_ACTIVITY_CHANGE";
export const NEW_ACTIVITY_SEND = "NEW_ACTIVITY_SEND";
export const NEW_ACTIVITY_SUCCESS = "NEW_ACTIVITY_SUCCESS";
export const NEW_ACTIVITY_FAILURE = "NEW_ACTIVITY_FAILURE";
